#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DASHBOARD_URL = process.env.TEXAS_WATER_DASHBOARD_URL ??
  "https://texas-water-api.ryan-shores.workers.dev/v1/dashboard";
const HISTORY_ROOT = "https://waterdatafortexas.org/reservoirs/individual";
const outputDirectory = process.env.TEXAS_WATER_BACKFILL_DIR ??
  join(".backfill", new Date().toISOString().replaceAll(/[:.]/g, "-"));
const rowsPerChunk = Number(process.env.TEXAS_WATER_BACKFILL_ROWS_PER_FILE ?? 1000);
const limit = Number(process.env.TEXAS_WATER_BACKFILL_LIMIT ?? 0);
let chunkNumber = 0;

if (!Number.isInteger(rowsPerChunk) || rowsPerChunk < 1) {
  throw new Error("TEXAS_WATER_BACKFILL_ROWS_PER_FILE must be a positive integer");
}

const dashboard = await fetchJSON(DASHBOARD_URL);
if (!Array.isArray(dashboard.reservoirs) || dashboard.reservoirs.length < 100) {
  throw new Error("Dashboard did not contain the expected statewide reservoir catalog");
}
const reservoirs = limit > 0 ? dashboard.reservoirs.slice(0, limit) : dashboard.reservoirs;

const statements = [];
let reservoirCount = 0;
let observationCount = 0;

for (let start = 0; start < reservoirs.length; start += 2) {
  const batch = reservoirs.slice(start, start + 2);
  const histories = await Promise.all(batch.map(async (reservoir, offset) => {
    if (!reservoir.id || !reservoir.slug) {
      throw new Error(`Dashboard reservoir ${start + offset + 1} is missing id or slug`);
    }
    const url = `${HISTORY_ROOT}/${encodeURIComponent(reservoir.slug)}-1year.csv`;
    const observations = parseCSV(await fetchText(url), reservoir.id);
    if (observations.length < 300) {
      throw new Error(`${reservoir.id} returned only ${observations.length} history rows`);
    }
    return { reservoir, observations };
  }));

  for (const { reservoir, observations } of histories) {
    for (const observation of observations) {
      statements.push(insertStatement(reservoir.id, observation));
      observationCount += 1;
      if (statements.length >= rowsPerChunk) await flushChunk(statements);
    }
    reservoirCount += 1;
    console.log(`${reservoirCount}/${reservoirs.length} ${reservoir.id}: ${observations.length} rows`);
  }
}

await flushChunk(statements);
await writeFile(
  join(outputDirectory, "manifest.json"),
  `${JSON.stringify({ dashboardURL: DASHBOARD_URL, reservoirCount, observationCount }, null, 2)}\n`,
);
console.log(`Wrote ${observationCount} observations for ${reservoirCount} reservoirs to ${outputDirectory}`);

async function flushChunk(buffer) {
  if (buffer.length === 0) return;
  await mkdir(outputDirectory, { recursive: true });
  chunkNumber += 1;
  const path = join(outputDirectory, `chunk-${String(chunkNumber).padStart(3, "0")}.sql`);
  const sql = `-- Generated by backend/scripts/backfill-history.mjs\n${buffer.join("\n")}\n`;
  await writeFile(path, sql);
  buffer.splice(0, buffer.length);
}

function insertStatement(reservoirID, observation) {
  const values = [
    sqlString(reservoirID),
    sqlString(observation.date),
    sqlNumber(observation.waterLevel),
    sqlNumber(observation.surfaceArea),
    sqlNumber(observation.reservoirStorage),
    sqlNumber(observation.conservationStorage),
    sqlNumber(observation.percentFull),
    sqlNumber(observation.conservationCapacity),
    sqlNumber(observation.deadPoolCapacity),
    "CURRENT_TIMESTAMP",
  ];
  return `INSERT INTO observations (reservoir_id, date, elevation, surface_area, reservoir_storage, conservation_storage, percent_full, conservation_capacity, dead_pool_capacity, ingested_at) VALUES (${values.join(", ")}) ON CONFLICT(reservoir_id, date) DO UPDATE SET elevation = excluded.elevation, surface_area = excluded.surface_area, reservoir_storage = excluded.reservoir_storage, conservation_storage = excluded.conservation_storage, percent_full = excluded.percent_full, conservation_capacity = excluded.conservation_capacity, dead_pool_capacity = excluded.dead_pool_capacity, ingested_at = excluded.ingested_at;`;
}

function parseCSV(body, reservoirID) {
  const lines = body.split(/\r?\n/).filter((line) => line.trim() && !line.startsWith("#"));
  const header = lines.shift()?.split(",");
  const expected = [
    "date", "water_level", "surface_area", "reservoir_storage",
    "conservation_storage", "percent_full", "conservation_capacity", "dead_pool_capacity",
  ];
  if (!header || header.join(",") !== expected.join(",")) {
    throw new Error(`${reservoirID} history CSV has an unexpected header`);
  }
  return lines.map((line, rowIndex) => {
    const values = line.split(",");
    if (values.length !== expected.length) {
      throw new Error(`${reservoirID} history row ${rowIndex + 2} has ${values.length} columns`);
    }
    return {
      date: values[0],
      waterLevel: values[1],
      surfaceArea: values[2],
      reservoirStorage: values[3],
      conservationStorage: values[4],
      percentFull: values[5],
      conservationCapacity: values[6],
      deadPoolCapacity: values[7],
    };
  });
}

function sqlString(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlNumber(value) {
  if (value === "" || value === undefined || value === null) return "NULL";
  const number = Number(value);
  if (!Number.isFinite(number)) throw new Error(`Invalid numeric value: ${value}`);
  return String(number);
}

async function fetchText(url, attempt = 1) {
  try {
    const response = await fetch(url, { headers: { "User-Agent": "TexasWaterBackfill/1.0" } });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return await response.text();
  } catch (error) {
    if (attempt >= 4) throw new Error(`Failed to fetch ${url}: ${error.message}`);
    await new Promise((resolve) => setTimeout(resolve, 500 * 2 ** (attempt - 1)));
    return fetchText(url, attempt + 1);
  }
}

async function fetchJSON(url) {
  return JSON.parse(await fetchText(url));
}
